### ISSUE TITLE
Overzicht blijft route 21-51 als onderbroken melden

### ISSUE THREAD

**Issue by dvdhoven** [vmarc/knooppuntnet#105]
Het algemene overzicht geeft voor Fietsen in Nederland een onderbroken route 21-51
Die route heb ik 16;33 gefixed
Als je op de route klikt, krijg je ook een overzicht dat de route oké is.

Kan die melding verwijderd worden:?

Alvast hartelijk dank,
Dick van den Hoven

**Comment by vmarc** [comment]
@dvdhoven dankjewel voor het melden van dit probleem!

The problem seems to be related to an upgrade of the Couchdb database software from version 2.3.1 to 3.1.0 that was done on friday. The way the database views work in this new version is a bit different, and it seems that there is still something wrong with that. I switched the frontend database from the one on the server in Germany to the database that runs on the Amsterdam server, and there the problem does not seem to exist. I believe you should not see the problem anymore at this moment.

Needs to be further investigated.

**Comment by dvdhoven** [comment]
Dank je  Marc

**Comment by dvdhoven** [comment]
Gisteren aan het eind van de middag had het overzicht in cijfers een hik, meldde eenvoudigweg Fout
Later werkte het weer, maar ik heb het gevoel dat niet alles gemeld wordt, wat er eerder wel gemeld wordtl. Dat is vaag, maar bijv. het aantal routewezen rwn in Nederland was even nul, terwijl het er 14 waren en daarna werden het er 7.
 Vanmorgen heb ik in Terschelling routes aan het netwerk toegevoegd en een paar andere fouten opgelost.
Eentje daarvan, een foute routenaam, werd wel bij het netwerk zelf gemeld, maar niet in het overzicht.
Changeset https://knooppuntnet.nl/nl/changeset/89388803/4150262 
Ik heb in deze changeset 13 routes aan het netwerk Terschelling toegevoegd, dat is anders dan de 7 die het overzicht meldt.
En nu na deze changeset blijft het overzicht nog steeds die 7 routes als routewees melden.
Ook heb ik een fixme=incomplete van 26-105 verwijderd, maar ook deze wordt nog steeds gemeld in het overzicht

Vriendelijke groeten,
Dick van den Hoven

**Comment by vmarc** [comment]
De problemen vanaf gisterenavond werden veroorzaakt door een nieuwe poging van mij om over te gaan op Couchdb 3.1.0. Ik heb zonet teruggeschakeld naar de vorige versie 2.3.1.

**Comment by vmarc** [comment]
De plannen om naar Couchdb 3.1.0 te gaan zijn voorlopig van de baan, alles terug naar 2.3.1 gebracht, prolbleem weg.
