### ISSUE TITLE
Analysis - Wrong map type displayed when a node has both an rwn_ref and an rcn_ref tag.

### ISSUE THREAD

**Issue by pelderson** [vmarc/knooppuntnet#111]
https://experimental.knooppuntnet.nl/nl/analysis/node/44813704 
Ik kom daar via analyse / wandelen / analyse per netwerk Nederland / Utrecht Groene Hart / Knooppunten / kies het eerste wandelknooppunt 44 in de lijst. 
Klik op Kaart en je ziet de kaart voor fietsen ipv wandelen. 
(Als ik via een "feit" in het wandelnetwerk een knooppunt open dat zowel rwn als rcn is gebeurt hetzelfde.)

Het is geen groot probleem dus kan rustig wachten tot een latere bugfix-release.

**Comment by vmarc** [comment]
This node is both a node in a hiking network (44) and a node in a cycling network (20). When a node belongs to two (or more) network types, the map shows both (all) network types.

The idea is that in this case you can use the layer switcher in the upper right corner to switch off the layer(s) of the network type(s) that you are not currently interested in.

You have to make this selection yourself. At this moment, the logic in the node map page is not really aware through which path you reached the page, and as such cannot derive the network type that you would be most likely interested in.

**Comment by pelderson** [comment]
I see, I missed the layer option! So what is confusing is that if both layers are active, the numbers of the bicycle network are shown, obscuring the walking network numbers. With thwe layer option it is even less urgent, but can this be an improvement request for the future?

**Comment by vmarc** [comment]
Implemented in release v3.0.4

In the node map page, when the node has more than 1 networkType (for example both 'hiking' and 'cycling'), we will try to only show the most relevant network layer. For example if the most relevant networkType is 'hiking', we will only show the 'hiking' layer, and leave the 'cycling' layer invisible.

What the most relevant network layer is, depends on the previous visited pages. 

- planner page (networkType taken from url)
- networkType specific analysis pages (networkType taken from url)
- route pages (networkType taken from route data)
- network pages (networkType taken from network data)

Each time the most relevant networkType changes, it is stored in the application local storage, so that it will get picked up even if opening a new browser tab or browser window.
