### ISSUE TITLE
Should we also put "survey:date" on node, or only on the relations?

### ISSUE THREAD

**Issue by hgcvm** [vmarc/knooppuntnet#116]
Should we also put "survey:date" on node, or only on the relations?
Because when I tried it on a node, I don't think the node appeared on the map in a different colour.
Expected behaviour, or not?

**Comment by vmarc** [comment]
@hgcvm I am glad you ask this question.

I was convinced that putting "survey:date" on a node would result in the node being shown in a different colour on the map, but when looking for an example node, I could not find any. It seems there is a problem in the software. I will look into it.

So, I would say: keep putting "survey:date" on the nodes, and I will make sure it will be shown.

@hgcvm for checking once the problem is solved: can you tell me the node that you did put "survey:date" on?

**Comment by hgcvm** [comment]
I have put survey:date on a few nodes already. For example some in the new node network "Poelberg - Meikensbossen":
https://www.openstreetmap.org/node/299289393
https://www.openstreetmap.org/node/4340378280
https://www.openstreetmap.org/node/469821938

**Comment by vmarc** [comment]
The node color now provides an indication about the most recent survey in the planner map when "Date last survey" mode is selected (the node survey information was missing in the tile data).

![issue116](https://user-images.githubusercontent.com/6596480/98946996-ebb41580-24f4-11eb-807c-d5142ee3573c.png)

**Comment by hgcvm** [comment]
Thanks for fixing this!
