### ISSUE TITLE
[Planner] Hiking network displayed at some zoomlevels on Motorboat and Canoe maps

### ISSUE THREAD

**Issue by pelderson** [vmarc/knooppuntnet#123]
When zooming in the Motorboat and Canoe maps, at a few  intermediate zoomlevels the hiking network is displayed. 
This is not the case wih the Inline-skate, Horse and Bicycle maps.

**Comment by vmarc** [comment]
@pelderson thanks for reporting this problem

I believe the wrong tiles were introduced during a tile experiment about one month ago. These tiles should have been automatically cleaned up after the experiment, but this did not happen due to a problem in the obsolete tile removal logic. This logic has been fixed, and the tiles should no longer be there now.

**Comment by pelderson** [comment]
Looks ok now! Thnx.
