### ISSUE TITLE
Display option to view map in every screen

### ISSUE THREAD

**Issue by MaartenDeen** [vmarc/knooppuntnet#14]
The option to view the map is only active in the Nodes screen. This is confusing. You should display this option in every screen when you have a network selected.

**Comment by vmarc** [comment]
@MaartenDeen thanks for reporting this problem.

The application has been changed to include a new separate menu option _"Map"/"Kaart"_ in the left side network menu. This makes it possible to navigate to the network map from any of the network related pages.

The map logic itself has been changed so that routes and nodes that do not belong to the network are shown in gray. This works only for zoom level 12 and above (which use vector based map tiles). Zoom levels below 12 use bitmap based tiles that do not allow for different coloring per network.

In the network nodes page (which you navigate to by selecting _"Nodes"/"Knooppunten"_ in the left network menu), there is still a separate option in the top application menu bar _"MAP"/"KAART"_, which shows the map with the network nodes. What is different in this map when comparing to the network map is that the map will only show the blue node markers for the nodes that are selected in the node filter in the left menu. The blue markers shown will vary with the choosen filter options.
