### ISSUE TITLE
Integrity check for nodes is going wrong

### ISSUE THREAD

**Issue by MaartenDeen** [vmarc/knooppuntnet#15]
The node facts page for [Venlo ](https://knooppuntnet.nl/en/network-facts/2240269) claims 97 issues with IntegrityCheckFailed. The first, for [node 01](https://knooppuntnet.nl/en/node/42446644) says 3 expected, 0 actual. On the node page there are no issues and there are 3 routes connected to the node.

**Comment by vmarc** [comment]
@MaartenDeen thanks for reporting this problem.

Some further information:

The 3 routes that are connected to this [network node](https://www.openstreetmap.org/node/42446644) are:

- [01-71](https://knooppuntnet.nl/en/route/8273166)
- [01-64](https://knooppuntnet.nl/en/route/8273165)
- [01-04](https://knooppuntnet.nl/en/route/8273164)

These routes are not included in the analysis (fact _"IgnoreTagBased"_) because they have a tag with key _osmc:symbol_.

The node page does not show these routes. The analysis logic thinks there are no routes connected to this node.

In Germany there are a lot of rwn routes that are not node network routes. In the past it was possible to recognize a lot of these routes because they had a tag with key _osmc:symbol_. At that time there were no node network routes in Belgium and The Netherlands with that tag.

The analysis logic has to be changed so that routes with _osmc:symbol_ tags are no longer excluded from analysis, and some other logic has to be found to still exclude a lot of routes in Germany that are not node network routes (e.g. ignore tag based exclusion logic as soon as a network node is found in the route relation or one of the route ways).

Also, some extra logic will be needed to report IntegrityCheckFailed on the node page (currently this information is only stored with the network data in the analysis database and not per individual node).

**Comment by vmarc** [comment]
The problem with excluding to much routes from analysis should have been fixed several versions ago.

With version v2.0.11, _"IntegrityCheckFailed"_ should now be properly reported on the node page.
