### ISSUE TITLE
No details of last update in details screen

### ISSUE THREAD

**Issue by MaartenDeen** [vmarc/knooppuntnet#16]
On the old website there are details of when the relation was last updated and when the website last updated the information from the route relation. The new website does not have this anymore.
It would be helpful if that information was included.

> Situation on: 2018-05-12 22:01:02
> Network last update: 2018-05-07 Traildino
> Relation last update: 2018-01-17 dvdhoven

**Comment by vmarc** [comment]
@MaartenDeen thanks for reporting this.

**About the timestamps**

The new website shows details about the network, route and node history. The idea at the time was that it was no longer necessary to also show the timestamps in the summary information. The history is displayed in reverse order, so ou can just look at the start of the history to see the timestamp of the latest change. to this information

But I can see how it could be helpful to include that information in the summary again.

The following information is still present in the data that is sent by the server to the browser, and requires minimal work to include again in the user interface:
- "situation on" timestamp (valid for networks, routes and nodes)
- network last update timestamp
- network relation last update timestamp
- route last updated timestamp
- node last updated timestamp

The logic to record the route relation last update timestamp was removed, but can be added again (requires a rebuild of the entire analysis database - no problem). 

I will add all timestamps again.

**About the user names**

In release [v2.0.4](https://github.com/vmarc/knooppuntnet/releases/tag/v2.0.4) all references to user names and user identifiers were removed from the system.

This was done as a first step in preparing for changes that are expected in the distribution of the metadata collected in OpenStreetMap. See Appendix A in the [OSM GDPR position page](https://wiki.openstreetmap.org/w/images/8/88/GDPR_Position_Paper.pdf). The second step in this preparation was to put the changeset information behind a login in release [v2.0.7](https://github.com/vmarc/knooppuntnet/releases/tag/v2.0.7). Depending on the outcome of the GDPR related changes to OpenStreetMap, more information may be removed in the future, or the user information may be re-added (although this would be a major change again, because at this moment the user information is completely absent in the analysis database).
