### ISSUE TITLE
Nodes and routes page only show a few items at a time

### ISSUE THREAD

**Issue by MaartenDeen** [vmarc/knooppuntnet#17]
The [nodes](https://knooppuntnet.nl/en/network-nodes/3138543) and [routes](https://knooppuntnet.nl/en/network-routes/3138543) pages only show 25 items at a time. Since these are long lists and you sometimes need a node or route at the end and because it is much more convenient to check for anomalies, it would be better to at least have an option to have all items on one page.
Having only a previous and next is also inefficient navigating when you sometimes have 30+ pages of nodes.

**Comment by vmarc** [comment]
@MaartenDeen thanks for reporting this.

Earlier versions of the application did include a menu option to set the page size. The option is still there for the _"changes"_ pages (towards the bottom of the left menu). During one of the refactorings, the option disappeared from the network nodes and network routes pages, without me being aware. So thanks for reporting. Luckily, the support for paging in the communication between browser and server is still there.

I think it is still useful to have the option to use small page sizes on slow devices like mobile phones. But being able to switch off paging when you are on a powerful computer would be useful.

TODO
- add page size option to network node list page
- add page size option to network route list page
- make the menu option more discoverable by putting it next to the _"next page"_/_"previous page"_ links, instead of in the left menu
- add the option _"all"_ to disable the paging mechanism and just show entire list
- store the page size as a user preference in browser local storage so that you do not have to select it again and again (as is the case with the menu option on the changes pages now)

**Comment by vmarc** [comment]
Implemented in v3.0.0
