### ISSUE TITLE
Integrity analysis - number of routes

### ISSUE THREAD

**Issue by UncleOwen** [vmarc/knooppuntnet#199]
Hi,

These 3 nodes [1](https://knooppuntnet.nl/en/analysis/node/2329110565) [2](https://knooppuntnet.nl/en/analysis/node/2730907032) [3](https://knooppuntnet.nl/en/analysis/node/2737829308) all show "The actual number of routes in this node (x) does not match the expected number of routes (y)." (with different values for x and y).

Last time I checked them they were fine. Also, on the [nodes overview page](https://knooppuntnet.nl/en/analysis/cycling/de/Pinneberg/nodes) they are not marked with a red E.

Has the calculation of expected number of routes changed? Is the "cluster relation" not counted anymore?

**Comment by vmarc** [comment]
@UncleOwen thanks for reporting this problem

Yes, the calculation of expected number of routes has changed in release 3.2 (active since September 5th).

Your observation is correct: the "cluster relation"s were not counted anymore.

This problem has been fixed today. Your example nodes do not show a problem anymore now.

Before the calculation change in 3.2, routes were counted per network and not across networks.  This is still a problem in network facts pages like [this one](https://www.knooppuntnet.nl/en/analysis/network/10953719/facts). Node [03](https://www.knooppuntnet.nl/en/analysis/node/1513454992) has 4 routes, but one of these routes is not part of network [Landkreis Dahme-Spreewald](https://www.knooppuntnet.nl/en/analysis/network/10953719). This problem still has to be solved.

**Comment by vmarc** [comment]
In release 3.2.5 (September 21st), the code was changed so that routes are counted across networks now.
