### ISSUE TITLE
[Feature Request] Handle coordinates in URL

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#202]
For e.g. documenting nodes, display a specific place on knooppuntnet… it will be useful to handle coordinates in URL.

Something like WaymarkedTrails:
- [https://knooppuntnet.nl/fr/map/hiking#map=18/45.1909/6.4429](https://hiking.waymarkedtrails.org/#?map=18!45.1909!6.4429) display a place
- [https://knooppuntnet.nl/fr/map/hiking#route=12088709](https://hiking.waymarkedtrails.org/#route?id=12088709) display a route between 2 nodes
- [https://knooppuntnet.nl/fr/map/hiking#route=12222887,12222814,12221609](https://hiking.waymarkedtrails.org/#routelist?ids=12222887,12222814,12221609) display routes from one node
- [https://knooppuntnet.nl/fr/map/hiking#guidepost=1364827595](https://hiking.waymarkedtrails.org/#guidepost?id=1364827595) display a guidepost
- [https://knooppuntnet.nl/fr/map/hiking#node=60726576](https://www.openstreetmap.org/node/60726576#map=19/45.20265/6.44446) display a node

Or BRouter: 
- [https://knooppuntnet.nl/fr/map/cycling#nodes=11,10,8,7,6](https://brouter.de/brouter-web/#map=14/50.7434/2.5966/standard,Waymarked_Trails-Cycling&lonlats=2.595969,50.753292;2.575496,50.747432;2.628048,50.732707)
<img width="33%" alt="Route planning in knooppuntnet" src="https://user-images.githubusercontent.com/2158081/134818222-24e69835-5886-4a13-a11e-50d3a0fd6d36.png"> <img width="33%" alt="Route planning in Brouter" src="https://user-images.githubusercontent.com/2158081/134818431-d105bbea-695e-49fc-bfdd-c32edc97c23f.png">

**Note:**

- URL could be without langage, so the map choose the user langage
https://knooppuntnet.nl/map/hiking#node=60726576

- Even shorter
https://knooppuntnet.nl/hiking#node=60726576

This is examples based on other OSM apps. It should be adapted to current analysis URLs:
- https://knooppuntnet.nl/fr/analysis/network/12280144
- https://knooppuntnet.nl/fr/analysis/route/12347802
- https://knooppuntnet.nl/fr/analysis/node/641839957

These URLs are similar to what I am looking for
- https://knooppuntnet.nl/fr/analysis/route/12253243/map
- https://knooppuntnet.nl/fr/analysis/node/641839957/map

…  but it's not possible to specify the exact view and it's not possible to easily copy/paste the URL from the map

**Comment by pelderson** [comment]
I support this idea! For Analysis, I use the URL to the object, no problem there. For PLanner, I often create a short dummy route and use the output link instead of a URL with coördinates. That's clumsy, and with any application update the itinerary link stops working.

**Comment by vmarc** [comment]
The "position" query parameter has been added to the url of the map pages.  The url with the position parameter is updated when panning the map or zooming in or out.

For example:

* [planner page with position parameter](https://knooppuntnet.nl/nl/map/cycling?position=51.44373862,4.46624221,13)

* [node page without position parameter](https://knooppuntnet.nl/nl/analysis/node/1181835685/map) (node in center, zoom level 18)

* [node page with position parameter](https://knooppuntnet.nl/nl/analysis/node/1181835685/map?position=51.47281464,4.48569252,15) (same node, but panned and zoomed out)

* [route page without position parameter](https://knooppuntnet.nl/nl/analysis/route/12714489/map) (positioned to fit route bounds)

* [route page with position parameter](https://knooppuntnet.nl/nl/analysis/route/12714489/map?position=51.47859561,4.50242998,14) (same route, but panned and zoomed out)

* [network page without position parameter](https://knooppuntnet.nl/nl/analysis/network/1741517/map) (positioned to fit network bounds upon first access, otherwise previous position from browser local storage)

* [network page with position parameter](https://knooppuntnet.nl/nl/analysis/network/1741517/map?position=51.44525373,4.46062338,14) (same network, but panned and zoomed in)

The planned route is now included in the "plan" query parameter in the planner url.

* [planned route](https://knooppuntnet.nl/nl/map/cycling?plan=peuqg-43hz7o-pfq7u)
