### ISSUE TITLE
Route displayed in Nodes list but not in routes list

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#204]
If a route is not a member of the network relation, it is displayed in the node list but not in the routes list.

Node [Passerelle de Lahr](https://knooppuntnet.nl/en/analysis/node/4212497010) and route [Chemin des rivières - Passerelle de Lahr](https://knooppuntnet.nl/en/analysis/route/13315611)

<img width="678" alt="Passerelle de Lahr" src="https://user-images.githubusercontent.com/2158081/136908660-4c67074c-92a2-4577-9cfe-d343123b31e0.png">

[Chemin des rivières - Passerelle de Lahr](https://knooppuntnet.nl/en/analysis/route/13315611) is not listed here

<img width="579" alt="Route list" src="https://user-images.githubusercontent.com/2158081/136909080-4dc3b044-0574-40f1-9a60-1a331f712d9b.png">

Like Nodes that aren't members of the network, routes should be listed
<img width="791" alt="Mockup of Route list" src="https://user-images.githubusercontent.com/2158081/136910260-b356f308-721d-44ac-95f5-6cc4b6960982.png">

**Comment by vmarc** [comment]
@pyrog the behaviour you see is it was intended

The network route list includes:
- routes that are member of the network relation

The network node list includes:
- nodes that are member to the network relation
- nodes that are member of route relations that are member of the network relation
- nodes that are member of ways that are part of route relations that are member of the network relation

In the network node list the "routes" column lists _all_ routes that arrive/depart in given node.The number of routes in this route list is intended to match the value specified in the (optional) _"expected_??n_route_relations"_ tag. The number specified there should match the number of all routes you see on the ground, independent of which network they belong to.

This is why the node route list will contain the routes that are part of the network, but also routes that are not part of the network.

I understand that this can be confusing, but the fact that a route arrives in or departs from a node in a network does not make it part of the network.

Agree?

P.S. I my mind network relations could become less important, I think would perhaps prefer to work with [Dole nodes](
https://knooppuntnet.nl/en/analysis/hiking/fr/Dole/nodes), instead of [Réseau pédestre du Grand Dole](https://knooppuntnet.nl/en/analysis/network/13305300).

**Comment by pyrog** [comment]
Sorry, I understood your comment later.

> I my mind network relations could become less important

In France, the important items are the routes. Nodes — in fact guideposts — are the physical way to link them on the field.
Why routes are so important : there is a sort of "law" the [Plan Départemental des Itinéraires de Promenade et de Randonnée (PDIPR)](https://www.sportsdenature.gouv.fr/publications/outils-mobilisables-pour-perenniser-acces-lieux-de-pratique/pdipr) that list path that are appropriates for public hikes, i.e:
- the path is public or there is an agreement with the owner to "allow" people to walk on)
- there is no hazard
- the city or a club maintains the path
- …

> I understand that this can be confusing

I confirm 😄 

> but the fact that a route arrives in or departs from a node in a network does not make it part of the network.

Factually, it does not make part of it but the route is physically connected to this network.
If knooppuntnet could list theses orphaned routes could be useful (this is similar to [free routes](https://www.knooppuntnet.nl/en/analysis/hiking/de/orphan-routes) for a country).
