### ISSUE TITLE
Routes named no-name

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#205]
If the name of one of the nodes of a route is missing, the route is called "no-name".
Could be called "A - 1234" if the first node is named  i.e. "A" and the last node is not named (and i.e. id=1234)

**Comment by vmarc** [comment]
The logic for route names has been changed (release 4 only) so that if there are no route tags with the route name, the route name is derived from the names of the nodes in the route.

This way there currently are no hiking routes in France anymore with RouteNameMissing.

I believe following routes would now benefit from not having the "note" tag anymore (in release 4):

- [13519504](https://experimental.knooppuntnet.nl/en/analysis/route/13519504)
- [13619463](https://experimental.knooppuntnet.nl/en/analysis/route/13619463)
- [13626627](https://experimental.knooppuntnet.nl/en/analysis/route/13626627)
- [11829059](https://experimental.knooppuntnet.nl/en/analysis/route/11829059)
- [11829061](https://experimental.knooppuntnet.nl/en/analysis/route/11829061)
- [13504960](https://experimental.knooppuntnet.nl/en/analysis/route/13504960)
- [13508056](https://experimental.knooppuntnet.nl/en/analysis/route/13508056)
- [13508061](https://experimental.knooppuntnet.nl/en/analysis/route/13508061)

Some of the above routes have names with three dashes in it, which makes it difficult for the analysis logic to derive the node names from the route name.

While this change enables the analysis of routes that do not have tags with the route name in it, leaving out these tags as a general rule is probably not a good idea I think, as it seems to make maintenance in JOSM more difficult.

Nodes without name are still not considered ok by the analysis.
