### ISSUE TITLE
Remember Analysis map settings

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#206]
Remember map settings:

Checkboxes
- Background
- Hiking
- Nodes
- Tilenames (256)

And lat, lon, zoom?

**Comment by vmarc** [comment]
@pyrog Remembering lat, lon, zoom in the analysis maps would not be an improvement I think. The application now automatically positions and zooms the map so that the network/route/node/change is shown in an optimal way.  

I am also having trouble to come up with scenarios where it would help if the layer settings were remembered.

Can you perhaps provide some examples where you see this useful?

**Comment by pyrog** [comment]
I'am not sure for lat, lon, zoom…
… but loosing the checkbox state is painful.

Sometime I don't want to see pins on nodes, even background too. When I check several nodes, routes with their maps, I must deselect each time each checkbox 😢

**Comment by pyrog** [comment]
Saving lat, lon, zoom is useful too:

1. display a map, zoom in to search i.e.an orphaned route.
2. fix the fact
3. refresh the webpage/map:
it's painful to search again the route to see if it's colour as changed

<img width="100%" alt="Orphaned route in a zoomed map" src="https://user-images.githubusercontent.com/2158081/137595754-f2e917ed-7823-49c6-b100-3c8c52f69747.png">

**Comment by pyrog** [comment]
Also store settings of  the hamburger menu (open/close).
With a "small" screen, this is painful too to click after each refresh on it to maximise the useful information.

PS: with opened menu, the route seem discontinued if labels are too long
<img width="50%" alt="Hamburger menu opened" src="https://user-images.githubusercontent.com/2158081/137764123-2f27ea7b-278c-410b-9cb9-6aa487cba898.png">
<img width="50%" alt="Hamburger menu closed" src="https://user-images.githubusercontent.com/2158081/137764126-e0de17d7-92c5-4bc9-a154-6bcde3840786.png">

**Comment by vmarc** [comment]
@pyrog ok, I understand better now, I will make the following changes:

- Remember the open/close state of the hamburger menu.

- On the network map page, remember the position and zoom level per network. Also include a button to zoom out so that the entire network is shown again (similar to the "R" button on the planner map that can be used to zoom to show the entire planned route).  The position and zoom level are remembered per network, so that when you go to the map of another network, the entire network is shown (and not the position of the previous network). 

  When going from network 1 to network 2, and then to network 1 again: should show the last used position and zoom of network 1, or the entire network again?

- I think I prefer to not make the  application remember the position and zoom level for the node map page, the route map page and the maps in the changes pages.  In these pages it makes less sense I think. Agree?

- Remember the layer checkbox states over all network, node and route pages.  Best to remember one state that applies to all  network, node and route pages I guess (not separate state per page type)? Better not to remember checkbox state for the maps in the changes pages? Or use same state there?

- Change the way the first column is displayed in the "route members" table: use scalable vector based svg images that adapt to the row height, instead of the current fixed height png images. This way the route will no longer seem discontinued if the row height becomes higher than the column 1 image height. The row height increases when text in any other column is split over multiple lines.

**Comment by vmarc** [comment]
Implemented in version 3.2.8 (can be tested on [experimental](https://experimental.knooppuntnet.nl/)):
- remember sidebar open/close state
- remember network map position and zoom (only for last viewed network, position/zoom lost when going to different network)
- button to zoom out to complete network in network map
- adapt route member link image height to row height (avoid gaps)
- remember map layer checkbox states (over all maps in network/route/node/subset/planner pages, not in changes pages)

**Comment by pyrog** [comment]
Thank you 😀
