### ISSUE TITLE
Support name tag (or ref tag) for nodes

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#217]
[Route 13331511](https://experimental.knooppuntnet.nl/en/analysis/route/13331511) is part of a regional walking network (`rwn`).
The start node [La Verrerie](https://experimental.knooppuntnet.nl/en/analysis/node/1803862875) is part of this network and tagged with `rwn_name=*`.
The end node [Fontaine des Près Bas](https://experimental.knooppuntnet.nl/en/analysis/node/448680349) is part of a local walking network (`lwn`) and tagged with `lwn_name=*`.

The analyser consider this route as broken because it can't find a `rwn_name=*` for the end note.

<img width="33%" alt="Map" src="https://user-images.githubusercontent.com/2158081/139302843-edd3435d-8557-4626-81a2-22b07d3a847a.png"> <img width="33%" alt="Details" src="https://user-images.githubusercontent.com/2158081/139303022-a7454b0d-9adb-4cb3-812a-48b158961fc4.png">

Using simply the tag `name=*` avoid this issue, simplify editing : 
- the user don't spend time to add the appropriate `xxn_` prefix
- editors (JOSM, iD…) could display the name of the node (also a lot of OSM apps including routers ?)
- this will be consistent with route and network relations that use the tag `name`

See https://github.com/vmarc/knooppuntnet/issues/203#issuecomment-944921071

**Comment by pyrog** [comment]
Also `network` tag is not required for route relations.
In France, a node network is a kind of "structured" local network, and multi practices (hiking, riding, mtb…).

So network is not really meaningful and using a `xxn_` prefix is really painful.

**Comment by pyrog** [comment]
Discussed in wiki : [KISS: keep it simple](https://wiki.openstreetmap.org/wiki/Talk:Node_Networks#KISS:_keep_it_simple).

Examples:

node | tag | Display label
-- | -- | --
[300161618](https://www.openstreetmap.org/node/300161618) | `lcn_ref = 97`<BR>`rcn_ref = 97` | 97
[9558783785](https://www.openstreetmap.org/node/9558783785)|<br>`lwn_name=Col de Chausseyras`<br>`name=Col de Chausseyras`<br>`natural=saddle `| Col de Chausseyras

KISS tagging:
node | tag | Display label
-- | -- | --
[300161618](https://www.openstreetmap.org/node/300161618) | `ref = 97`| 97
[9558783785](https://www.openstreetmap.org/node/9558783785)|<br>`name=Col de Chausseyras`<br>`natural=saddle `| Col de Chausseyras

Of course, one could choose the preferred tagging 😄 

In case if both tags are present, KPN choose the prefixed tag:
node | tag | Display label
-- | -- | --
[9558783785](https://www.openstreetmap.org/node/9558783785)|<br>`lwn_name=Chausseyras`<br>`name=Col de Chausseyras`<br>`natural=saddle `| Chausseyras

**Comment by pyrog** [comment]
I searched nodes with different `xxn_ref`, `xxn_name` tags (or a mix of both).

Unless I'm mistaken, there are only [26 nodes](https://overpass-turbo.eu/?Q=%2F%2F%5Bout%3Ajson%5D%5Btimeout%3A2500%5D%3B%0A%2F%2F%7B%7BgeocodeArea%3AFrance%7D%7D-%3E.searchArea%3B%0A%0A%5Bout%3Acsv%28%3A%3Aid%2Clcn_ref%2Crcn_ref%29%5D%5Btimeout%3A2500%5D%3B%0Anode%5B%22network%3Atype%22%3D%22node_network%22%5D%5B%22rcn_ref%22%5D%5B%22lcn_ref%22%5D%3B%0A%2F%2F%28area.searchArea%29%3B%0A%0Aout+geom%3B&C=51.076135%3B3.715782%3B11) in the world, all in the city of Gent in Belgium.
All have the same value for `lcn_ref` and `rcn_ref `tags !

So please, handle also "simple" and standard tags  : it will be easier for all people in the world, even in Belgium and Netherlands 😎 

<img width="50%" alt="Overpass query" src="https://github.com/vmarc/knooppuntnet/assets/2158081/1c6c24c5-dfd9-431d-b89c-a54689d97777">

**Comment by vmarc** [comment]
In node network tagging (and in the knooppuntnet analysis logic) it is important to be able to differentiate between what kind of network we are dealing with:

- hiking
- cycling

and also:

- horse riding
- motorboat
- canoe 
- inline skating

For a route the documented OSM way to do this is using the _"network"_ tag (second letter of the xxn value), for a node this is done with the second letter in the  _"xxn_ref"_ tag (or variations of this tag).

In the node networks in Belgium and The Netherlands the guideposts on the ground look very different, and it makes sense to reflect this in the tagging.

- [example cycling node](https://wiki.openstreetmap.org/wiki/File:Fietsknooppuntennetwerk_Haaglanden_(1).JPG)

- [example hiking node](https://wiki.openstreetmap.org/wiki/File:Kasterlee_-_Wandelknooppunt_74_-_Belgi%C3%AB.jpg)

A cycling map/planner shows cycling nodes, a hiking map/planner shows hiking nodes.

So, some tagging to differentiate between cycling and hiking nodes is needed.  The currently documented way is to use the _"xxn"_ values for this.  Perhaps it is a bit unfortunate that this _"xxn"_ value also contains the network _"scope"_ (local, regional, national, international).  But since it is there, checks are done to make sure that the scope of the nodes match the scope of the route. 

---

In the knooppuntnet database there are currently 3820 nodes that are both hiking and cycling nodes.  For none of these nodes the cycling node name and the hiking node name is the same.

Following mongodb query was used to find the 3820 nodes that are both hiking and cycling nodes:

```
[
  {
    $match: {
      $and: [
        {
          labels: {
            $eq: "active"
          }
        },
        {
          labels: {
            $eq: "network-type-hiking"
          }
        },
        {
          labels: {
            $eq: "network-type-cycling"
          }
        }
      ]
    }
  },
  {
    $count: "total"
  }
]
```

Extra filter to find nodes where cycling and hiking node name is the same:

```
  {
    $match:
      {
        "names[0].name": {
          $eq: "$names[1].name"
        }
      }
  }

```

Filter to find nodes where cycling and hiking node name is not the same:

```
  {
    $match:
      {
        "names[0].name": {
          $ne: "$names[1].name"
        }
      }
  }

```


---

All this to say that I think the _"simple"_ and _"standard"_ tags are not sufficient (and also not _"standard"_) for node networks.

**Comment by pyrog** [comment]
In France, I think that most (exactly 39/19563 so 0,2%) nodes (in practice guideposts) shared with several "sports"  have only one name or ref.
See examples below.

> All this to say that I think the "simple" and "standard" tags are not sufficient (and also not "standard") for node networks.

Again my suggestion is when there is no `xxn_name` tags accept `name` tag and no `xxn_ref` use `ref` tag.
Again tags name or ref are standard for most software (editors…).

node_network scheme was written by and for Nederland peoples 😉 

> In the knooppuntnet database there are currently 3820 nodes that are both hiking and cycling nodes. 

How many in France, Germany… ?
For France where exactly ?
I find only [39 nodes](https://overpass-turbo.eu/s/1MYN) with `rcn_ref` and `rwn_ref` in the north of the country.

### Examples
from https://overpass-turbo.eu/s/1MYL

- [Sous Chambotte](https://www.openstreetmap.org/node/3417440187)
<img width=25%  src="https://avf.asso.fr/voiron/wp-content/uploads/sites/357/2019/06/P1040079.jpg">

- [Chaillol Village](https://www.openstreetmap.org/node/11915121018)
<img width=25%  src="https://api.panoramax.xyz/api/pictures/65f1da2f-5b17-451d-b727-bc682d9c6b8a/hd.jpg">

- [Cimetière d'Aurel](https://www.openstreetmap.org/node/8793160867)
<img width=25%  src="https://api.panoramax.xyz/api/pictures/6259f574-6f7f-4305-976a-0b4aef503189/hd.jpg">

- [AU037_02](https://www.openstreetmap.org/node/9045268697)
<img width=25%  src="https://api.panoramax.xyz/api/pictures/cd257009-dcc9-4b5d-bbc2-6342d60581dc/hd.jpg">

**Comment by vmarc** [comment]
I can confirm your number for France. When restricting the MongoDB query to France it finds 40.  In Germany there are 54.

**Comment by pyrog** [comment]
The [last node](https://knooppuntnet.nl/fr/analysis/node/495412493) part of an hiking and cycling network a the same reference in each one.

<img width="33%" alt="Capture d’écran 2024-06-17 à 13 51 52" src="https://github.com/vmarc/knooppuntnet/assets/2158081/c40a217a-bed2-48b0-a880-c0748d13106a">
