### ISSUE TITLE
Geometry of a municipality

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#225]
For the city of Dole, this is not the city itself but a bigger administrative boundary (Dole, Arbois…)

<img width="920" alt="Capture d’écran 2021-11-08 à 17 25 38" src="https://user-images.githubusercontent.com/2158081/140779812-fb390d84-bd1c-4834-b13a-56172b2b8ad1.png">

**Comment by pyrog** [comment]
[Dole](https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=148676&class=boundary) (admin level 8)

<img width="806" alt="Capture d’écran 2021-11-08 à 17 38 42" src="https://user-images.githubusercontent.com/2158081/140781993-9acd791e-4f47-4e5b-8fef-cbb78b27ddd0.png">

[Dole](https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=1684776&class=boundary) (admin level 7)
<img width="814" alt="Capture d’écran 2021-11-08 à 17 39 34" src="https://user-images.githubusercontent.com/2158081/140782125-6372ec6c-b368-483d-ba7a-34f600ae7623.png">

**Comment by pyrog** [comment]
In France, usually node networks are operated by _communauté de communes_ (a set of cities).
They aree tagged with `boundary=local_authority` and `local_authority:FR=CC`.

Example: [Communauté de communes Arbois, Poligny, Salins – Cœur du Jura](https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=6889776&class=boundary)

<img width="743" alt="Capture d’écran 2021-11-08 à 17 45 30" src="https://user-images.githubusercontent.com/2158081/140783125-b3514d95-0d7c-4966-9464-f200073e629b.png">

**Comment by vmarc** [comment]
Currently, knooppuntnet uses administrative bounderies level 4, 6 and 7 under level 3 administrative boundary _"Metropolitan France"_ (relation 1403916).  This results in a location tree with 190 locations.

From [OSM wiki](https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative) :
- level 4 = Régions
- level 6 = Départements
- level 7 Arrondissements

The actual boundaries were downloaded from [osm-boundaries.com](https://osm-boundaries.com/).


The above boundary levels were choosen more or less arbitrarely to form a tree that is one the one hand detailed enough, but on the other hand also does not have too many branches.

There seem to be 995 locations that match overpass query: relation["boundary"="local_authority"]["local_authority:FR"="CC"]. So these would form the most detailed locations in the tree. What would be the other boundaries that would form a complete location tree?

**Comment by pyrog** [comment]
level 7 is not useful in France.

The complete location tree could be:
tag | description
--|--
admin_level=4 | Régions
admin_level=6 | Départements
local_authority:FR=CC|Communautés de communes
admin_level=8|Villes

**Comment by pyrog** [comment]
[Saint-Claude](https://knooppuntnet.nl/en/analysis/hiking/fr/Saint-Claude/map) and [Lons-le-Saunier](https://knooppuntnet.nl/fr/analysis/hiking/fr/Lons-le-Saunier/map ) (arrondissements)
Not useful 😢 

<img width="33%" alt="Saint-Claude" src="https://user-images.githubusercontent.com/2158081/141672226-11465c8d-c467-4ed9-9156-1e1b7209d66f.png"> <img width="33%" alt="Lons-le-Saunier" src="https://user-images.githubusercontent.com/2158081/141672491-f327f2e6-c7ce-4805-9fe3-8ce58f4cac54.png">


Terre d'Émeraude Communauté ([overpass query](https://overpass-turbo.eu/s/1cZZ))
This community is the operator of the physical node network.

<img width="50%" alt="Terre d'Émeraude Communauté" src="https://user-images.githubusercontent.com/2158081/141672252-832a023b-7306-491c-9b15-997fe23a764d.png">

**Comment by pyrog** [comment]
@vmarc Stéphane suggest to use `admin_level=7` in France for communautés de communes.
We will discuss this with the french community.

**Comment by vmarc** [comment]
@pyrog thanks for discussing this

**Comment by pyrog** [comment]
@vmarc unfortunately communautés de communes (CDC) aren't really administrative parts of department.
They could span over departments.

So for France, could you remove admin_level=7 and keep department (101 in France), CDC ([995](https://fr.wikipedia.org/wiki/Communauté_de_communes#Nombre_de_communautés_de_communes)) or cities (around 36 000 !)?

**Comment by vmarc** [comment]
This weekend, I looked into what it would mean to introduce _"Communauté de communes"_ (CDC) in knooppuntnet.

The picture below shows the CDC's as found in OpenStreetMap, in interpreted by knooppuntnet code: 
- country boundary in blue
- department boundary in red
- CDC's in grey

There are white gaps in the map. It looks like not all all _"communes"_ belong to a CDC. So, the next step will be to decide wether/how to include the _"communes"_ (administrative boundary level 8).  One option would be to only include the _"communes"_ that are not in a CDC, and have these as part of the departments, next to the CDC. The other option is to include all _"communes"_, but I guess that will require techincal changes to the user interface because there are so many of them. 


There are 13 CDC's that belong to multiple departements (colored green in the picture below):

1647710 "Communauté de communes des Deux Rives"
- 5%  New Aquitaine
- 94%  Occitania

1663513 "Communauté de communes d'Aire-sur-l'Adour"
- 67%  New Aquitaine
- 32%  Occitania

1992967 "Communauté de communes du Pays Houdanais"
- 21%  Centre-Loire Valley
- 78%  Ile-de-France

2155090 "Communauté de communes Vaison Ventoux"
- 7%  Auvergne-Rhône-Alpes
- 92%  Provence-Alpes-Côte d'Azur

3031637 "Communauté de communes des Villes Sœurs"
- 39%  Hauts-de-France
- 60%  Normandy

3402933 "Communauté de communes du Pays de Nay"
- 90%  New Aquitaine
- 9%  Occitania

3406146 "Communauté de communes Cèze Cévennes"
- 7%  Auvergne-Rhône-Alpes
- 92%  Occitania

3438430 "Communauté de communes Enclave des Papes - Pays de Grignan"
- 66%  Auvergne-Rhône-Alpes
- 33%  Provence-Alpes-Côte d'Azur

3438840 "Communauté de communes Ventoux Sud"
- 7%  Auvergne-Rhône-Alpes
- 92%  Provence-Alpes-Côte d'Azur

6852116 "Communauté de communes Le Grand Charolais"
- 7%  Auvergne-Rhône-Alpes
- 92%  Bourgogne-Franche-Comté

6883410 "Communauté de communes Interrégionale Aumale - Blangy-sur-Bresle"
- 18%  Hauts-de-France
- 81%  Normandy

6952860 "Communauté de communes Maine Saosnois"
- 5%  Normandy
- 94%  Pays de la Loire

6983394 "Communauté de communes Adour-Madiran"
- 15%  New Aquitaine
- 84%  Occitania

CDC's belonging to multiple departements do not necessarily have to be a problem I think. 


![fr-cc](https://user-images.githubusercontent.com/6596480/142769415-2393e6da-45d2-45bb-926a-e95f1251c11f.png)

---
Here is a view of the existing location definitions in France (admin levels 4 and 7):

![fr](https://user-images.githubusercontent.com/6596480/142769530-7f3744b6-5adb-4a38-8c2c-b367a8e4b7be.png)

---
Netherlands:
![nl](https://user-images.githubusercontent.com/6596480/142769537-f555f059-5712-427a-94c2-7e80b37cdc2f.png)

---
Germany:
![de](https://user-images.githubusercontent.com/6596480/142769555-9f728364-e150-4193-a95f-fca88859cfc5.png)

---
Spain:
![es](https://user-images.githubusercontent.com/6596480/142769586-06f79bf6-66df-47ca-85e0-0b75dabbf90f.png)

---
Austria:
![at](https://user-images.githubusercontent.com/6596480/142769691-c1a907a2-79d0-40b8-b9bc-a7e2fae3464f.png)

---
Belgium:
![be](https://user-images.githubusercontent.com/6596480/142769695-73f58fab-1c78-4bb7-b4a7-3e23ea3da796.png)

**Comment by pyrog** [comment]
Thank you for this great detailed analysis 😃 


> There are white gaps in the map. It looks like not all all "communes" belong to a CDC.

yes

> There are 13 CDC's that belong to multiple departements 
> CDC's belonging to multiple departements do not necessarily have to be a problem I think.

It is for the french community to use admin level 7, but if it's not an issue for knooppuntnet why not 😃 
There is still a issue with _CDC_ and (less) with _communes_ : they could merge or be dissolved in the time.
_Départements_ are more stable.

So if knooppuntnet could "managed" political movement (_communes_ or _CDC_ merging, _CDC_ dissolving) : let's go.
If it's too complex, just keep _régions_ and _départements_

> So, the next step will be to decide wether/how to include the "communes" (administrative boundary level 8). One option would be to only include the "communes" that are not in a CDC, and have these as part of the departments, next to the CDC. 

The tree could be:
* _région_
   *  _département_
      * _CDC_ or isolated _communes_
         *  _communes_

If you decided to use this tree, _CDC_ that are across _département_ boundaries must be visible in both _départements_.

* Auvergne-Rhône-Alpes
   * Drôme
      * Communauté de communes Enclave des Papes - Pays de Grignan
         * Chamaret
         * Chantemerle-lès-Grignan
         * Colonzelle
         * Grignan
         * Montbrison-sur-Lez
         * Montjoyer
         * Montségur-sur-Lauzon
         * Le Pègue
         * Réauville
         * Roussas
         * Rousset-les-Vignes
         * Saint-Pantaléon-les-Vignes
         * Salles-sous-Bois
         * Taulignan
         * Valaurie

* Provence-Alpes-Côte d'Azur
   * Vaucluse
      * Communauté de communes Enclave des Papes - Pays de Grignan
         * Grillon
         * Richerenches
         * Valréas
         * Visan

<img width="33%" src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Localisation_CC_Enclave_des_Papes-Pays_de_Grignan_dans_la_Dr%C3%B4me%2C_France.svg/langfr-560px-Localisation_CC_Enclave_des_Papes-Pays_de_Grignan_dans_la_Dr%C3%B4me%2C_France.svg.png">

**Comment by vmarc** [comment]
One step further in the analysis: tried to fill in the gaps between CDC's with admin_level=8 boundary locations (based on geometries).

Looking at the graphical output, the logic is not 100% yet I think.  9457 locations were needed to fill in the gaps, which is a lot more than I expected/hoped.

![fr-cc-with-communes](https://user-images.githubusercontent.com/6596480/143138655-b33da15e-b686-4683-988e-3bd71ddb72d0.png)

**Comment by vmarc** [comment]
I probably should have filtered on _"boundary=administrative"_ in the "admin_level=8" relations, so that _"religious_administration"_ is excluded.

|boundary tag value|admin_level=8 relation count|
|---|---|
|administrative_fraction | 2|
|religious_administration | 751|
|administrative | 35059|

**Comment by vmarc** [comment]
Futher analysis has resulted in this [location tree](https://raw.githubusercontent.com/vmarc/knooppuntnet/develop/docs/france.md).

See also: [higher resolution image](https://github.com/vmarc/knooppuntnet/blob/develop/docs/france.png).

![france-small](https://user-images.githubusercontent.com/6596480/143681933-a92042ce-2515-4ea1-9088-8216e7d7d520.png)

**Comment by NicolasGrosjean** [comment]
Thanks @vmarc for all your work.

@pyrog asked me to check the map near Grenoble and I see that the [Grenoble-Alpes Métropole](https://www.openstreetmap.org/relation/2102885#map=12/45.2227/5.7235) and the [Communauté d'agglomération du Pays Voironnais](https://www.openstreetmap.org/relation/2101809#map=11/45.2995/5.6731) whereas it shouldn't.

Maybe you should use the tag [local_authority:FR](https://wiki.openstreetmap.org/wiki/Key:local%20authority:FR?uselang=en).

**Comment by StephaneChatty** [comment]
Hi! Thanks for the "région / département / communauté de communes" scheme, that's exactly what we need!

I have had a look around Toulouse and whereas various "communauté de communes" are correct, it seems that Toulouse métropole and SICOVAL are missing and their individual "communes" appear as orphans.  That is weird, because these are the largest communities in Haute-Garonne.

More generally, I wonder whether you could dispense with the "commune" level. Various arguments for that:
 - there are > 30.000 communes in France, that's a lot
 - only 3 of them are not included in a communauté de communes (maybe 6 if you consider Paris, Lyon and Marseille)
 - in most places, it is the communauté de communes who deal with outdoor routes

**Comment by vmarc** [comment]
The location definitions for France in knooppuntnet have been investigated one more time.

As a result of a suggestion by @pyrog in telegram, instead of only looking for value _"CC"_ (Community of communes) in the tag with key [local_authority:FR](https://wiki.openstreetmap.org/wiki/Key%3Alocal_authority%3AFR), the analysis is now also looking at _"CU"_, _"CA"_ and _"metropole"_. So instead of just CDC's we are now working with the more general intermunicipalities (_"Intercommunalité"_).

| value | meaning |
| ------- | ------------ |
| CC | Community of communes |
| CU | Urban community |
| CA  | Aglomeration community |
| metropole | Metropole |

Analysis shows that all except 4 municipalities belong to one of these intermunicipalities.These municipalities are now ignored in the analysis (see "aucune" in wikipedia page, righthand sidebar under "Administration",  "Intercommunalité" ):

| relation  | siren | siren |name |
| ---------- | ------ | -------- | ----- |
| [399669](https://www.openstreetmap.org/relation/399669) | [wikipedia](https://fr.wikipedia.org/wiki/%C3%8Ele-de-Br%C3%A9hat) | 22016 | Île-de-Bréhat |
| [278723](https://www.openstreetmap.org/relation/278723) | [wikipedia](https://fr.wikipedia.org/wiki/fr:%C3%8Ele-de-Sein) | 29083 | Île-de-Sein |
| [156066](https://www.openstreetmap.org/relation/156066) | [wikipedia](https://fr.wikipedia.org/wiki/fr:L'%C3%8Ele-d'Yeu) | 85113 | L'Île-d'Yeu |
| [659733](https://www.openstreetmap.org/relation/659733) | [wikipedia](https://fr.wikipedia.org/wiki/fr:Ouessant) | 29155 | Ouessant |

The new location definitions, including the municipalities, is documented in:
- [tree](https://raw.githubusercontent.com/vmarc/knooppuntnet/develop/docs/france-2.md)
- [image](https://raw.githubusercontent.com/vmarc/knooppuntnet/develop/docs/france-2.png)

@pyrog @StephaneChatty  With (almost) no municipalities without intermunicipality (intercommunalité), I think we can drop the municipality (commune) level in the knooppuntnet location tree?
- [tree](https://raw.githubusercontent.com/vmarc/knooppuntnet/develop/docs/france-3.md)
- [image](https://raw.githubusercontent.com/vmarc/knooppuntnet/develop/docs/france-2.png)


One more thing to look into: "Métropole du Grand Paris" ([osm](https://www.openstreetmap.org/relation/5814660)) looks bigger than the departements it belongs to:
- `fr-1-75` Paris  (1) ([osm](https://www.openstreetmap.org/relation/71525))
  - `fr-2-200054781` Métropole du Grand Paris
- `fr-1-92` Hauts-de-Seine  (1) ([osm](https://www.openstreetmap.org/relation/7449))
  - `fr-2-200054781` Métropole du Grand Paris
- `fr-1-93` Seine-Saint-Denis  (1) ([osm](https://www.openstreetmap.org/relation/7389))
  - `fr-2-200054781` Métropole du Grand Paris
- `fr-1-94` Val-de-Marne  (1) ([osm](https://www.openstreetmap.org/relation/7458))
  - `fr-2-200054781` Métropole du Grand Paris

I think all will be good with just not including "Métropole du Grand Paris" in the tree.

**Comment by pyrog** [comment]
The 4 cities/island should be kept. I don't know if they have yet node networks, but potentially yes.

Métropole du Grand Paris seem too big to be useful so it could be removed from the tree.
(We should ask to local contributors).

You could drop the municipality level, but keep the 4 islands in the tree (at the same level than intermunicipality).

  - `fr-1-22` Côtes-d'Armor  (10)
    -  `fr-1-22016` Île-de-Bréhat
    - …
  - `fr-1-29` Finistère  (21)
    - `fr-1-29083`  Île-de-Sein
    - `fr-1-29155 `  Ouessant
    - …
  - `fr-1-85` Vendée  (19)
    - `fr-1-85113 `L'Île-d'Yeu
    - …


Note: the reference for communes is [COG](https://fr.wikipedia.org/wiki/Code_officiel_géographique), commonly called "INSEE" and called "code commune" in Wikipedia infobox. OSM tag `ref:INSEE`. They also have a SIREN (but not always tagged in OSM).
Inter municipalities have only a SIREN because they are administrative entities.

**Comment by pyrog** [comment]
I forgot, could you add [DROM](https://fr.wikipedia.org/wiki/Département_et_région_d%27outre-mer#Départements_et_régions_d'outre-mer_actuels) too. Some have node networks.
  - `fr-?-971` Guadeloupe  (971)
  - `fr-?-972` Martinique  (972)
  - `fr-?-973` Guyane  (973)
    -  `fr-?-249730045` Communauté d’agglomération du Centre Littoral
    -  `fr-?-249730052` Communauté de communes de l'Est guyanais
    -  `fr-?-249730037` Communauté de communes de l'Ouest guyanais
    -  `fr-?-200027548` Communauté de communes des Savanes
  - `fr-?-974` La Réunion  (974)
    -  `fr-?-249740119` Communauté intercommunale du Nord de la Réunion
    - `fr-?-249740093` Communauté intercommunale Réunion Est
    - `fr-?-249740085`Communauté d’agglomération du Sud
    - `fr-?-249740077`Communauté intercommunale des Villes solidaires
    - `fr-?-249740101`Territoire de la Côte Ouest
  - `fr-?-976` Mayotte (976)

**Comment by pyrog** [comment]
Also, I think that communes shouldn't completely removed from KN.
On the field, we know municipality names, not inter municipality names.

So municipality should be still searchable by name, even if the tree display "only" inter municipalities.

What is simpler, clearer ?
- Keep all municipalities in the tree ?
- Remove them (except the 4 islands) ?

Does keeping municipalities have an impact on data consumption and performances ?

**Comment by vmarc** [comment]
@pyrog thanks for your feedback! and sorry for my slow response...

> Does keeping municipalities have an impact on data consumption and performances ?

Yes and no.

Yes, keeping the municipalities means more work on the server and extra data in the analysis database. But no, that does not matter too much. The server and database should be able to easily handle that.

Keeping the municipalities has the most impact on the user in the browser when displaying the entire location tree. This is at this moment unacceptably slow:
- go to [location tree](https://experimental.knooppuntnet.nl/fr/analysis/hiking/fr)
- make sure "Sélectionnez dans l'arborescence" is selected
- click "Tout" radio button
- click "Développer tout"
- dialog opens, click "Yes"
- click "Tout réduire"
- click "Développer tout", and "Yes" again
- navigate away from the tree page, for example by clicking "Recherce par nom" in the sidebar

On my mobile phone some of these actions take up to 30 seconds.  "Tout réduire" and "navigating away from the location tree page" both take more time than you would expect.

> The 4 cities/island should be kept.

Ok.

> Métropole du Grand Paris seem too big to be useful so it could be removed from the tree.

Ok, I will hardcode this.

> You could drop the municipality level, but keep the 4 islands in the tree (at the same level than intermunicipality).

Ok, I will hardcode the 4 islands at same level of intermunicipality.

> What is simpler, clearer ?
> - Keep all municipalities in the tree ?
> - Remove them (except the 4 islands) ?

Removing sounds like the more simple option :)

> Also, I think that communes shouldn't completely removed from KN.
> On the field, we know municipality names, not inter municipality names.
> So municipality should be still searchable by name, even if the tree display "only" inter municipalities.

Ok, I will change the code to not show the municipalities in the tree anymore (I expect that will avoid the bad performance described above), but still include the municipalities for searching locations by name.


> Note: the reference for communes is COG, commonly called "INSEE" and called "code commune" in Wikipedia infobox. OSM tag ref:INSEE. They also have a SIREN (but not always tagged in OSM).
> Inter municipalities have only a SIREN because they are administrative entities.

The [logic](https://github.com/vmarc/knooppuntnet/blob/develop/server/src/main/scala/kpn/core/tools/location/LocationBuilderFrance.scala) currently uses "ref:INSEE" for municipalities and departments, and "ref:FR:SIREN" for intermunicipalities.


> I forgot, could you add DROM too. Some have node networks.

When you zoom out completely and pan arround a bit in the [planner](https://knooppuntnet.nl/nl/map/hiking), you can see the bounds of the area for which background tiles are generated. Even within these bounds, details are only included for France, Spain, Germany, Austria, Netherlands and Belgium.  This currently does not include the France oversees areas. For now (release 4.0), I would prefer to limit the knooppuntnet scope this area. Also, when looking for relations with _network:type=node_network_ in the overseas areas, I could not find any.

![osm](https://user-images.githubusercontent.com/6596480/153660376-9864b3f3-e382-4aa6-80d4-a8877fccd041.png)


From Telegram:
> Métropole de Lyon should be in Rhône ?
> This is an administrative special case. This metropole cover all the department

I am not sure somethings still needs be done here.

[Métropole de Lyon](https://www.openstreetmap.org/relation/4850450) does not seem to overlap [Rhône](https://www.openstreetmap.org/relation/4850451)?

**Comment by pyrog** [comment]
> Also, when looking for relations with network:type=node_network in the overseas areas, I could not find any.

Not yet, but we have a new contributor in La Réunion

> [Métropole de Lyon](https://www.openstreetmap.org/relation/4850450) does not seem to overlap [Rhône](https://www.openstreetmap.org/relation/4850451)?
AFAIK it doesn't (it should have the same geometry as the Rhône department).

Thank you again for your work 😎
