### ISSUE TITLE
Hiking network Brabantse Wal sorted before ' and A

### ISSUE THREAD

**Issue by A67-A67** [vmarc/knooppuntnet#23]
For some reason the hiking network Brabantse Wal is sorted at the first place in the [Dutch hiking network list](https://knooppuntnet.nl/nl/networks/nl/rwn), before the apostrophe and A.

**Comment by vmarc** [comment]
The reason for having the network _Brabantse Wal_ at the top of the list goes back to 2013. This is when I started my OpenStreetMap activities with trying to map this network. I felt the need to write some code to verify wether my own mapping was according to the rules I found in the Wiki pages. Later on, this analysis logic was expanded to also cover other hiking networks, later also bicycle networks, etc. This kept evolving into knooppuntnet as it is now.

All that time I kept _Brabantse Wal_ at the top of the list, just because this was handy for myself. The sorting logic now has been changed to no longer give priority to my favorite network.
