### ISSUE TITLE
Localise cities

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#232]
In this example, **Dunkirk** is the english name of **Dunkerque**

<img width="545" alt="Capture d’écran 2021-11-11 à 12 54 10" src="https://user-images.githubusercontent.com/2158081/141293734-39bb11f0-0f6b-4c51-8429-b49cc86c8488.png">

**Comment by pelderson** [comment]
I have this issue with some Dutch names as well. I will investigate, see if it is a data issue.

**Comment by pyrog** [comment]
This is a knoopuntnet issue because it ask Nominatim to return english names.
See [map-geocoder.ts#L9](https://github.com/vmarc/knooppuntnet/blob/1701f0af06678731b095be3d999a3d25c80ccbb3/client/src/app/components/ol/domain/map-geocoder.ts#L9).

Dunkirk data:
- https://www.openstreetmap.org/relation/139610
- https://www.openstreetmap.org/relation/1643683

**Comment by vmarc** [comment]
The location based analysis does not use Nomatim.

The language parameter in [map-geocoder.ts](https://github.com/vmarc/knooppuntnet/blob/1701f0af06678731b095be3d999a3d25c80ccbb3/client/src/app/components/ol/domain/map-geocoder.ts#L9) only affects the action behind the search button in the planner map. A nice enhancement will be to use the values "de", "fr" and "en" ("nl" not supported) instead of always "en".  I will look into that.

![image](https://user-images.githubusercontent.com/6596480/141699736-67afffa4-6ab8-477e-af9c-f84575841f8b.png)

---

The location selection page has been changed to use localized names.  

Still missing at this moment: localized names in the location page titles, breadcrumbs and browser tab texts. I am still thinking about how this  can be done. Possibly the url of the location pages will have to change also.

---
English:

![image](https://user-images.githubusercontent.com/6596480/141699345-6c6b3a2c-888b-47af-9519-8e04c8974414.png)

---
Dutch:

![image](https://user-images.githubusercontent.com/6596480/141699379-87f8a6ab-d9f2-4d04-b3d7-586c58fcf830.png)

---
French:

![image](https://user-images.githubusercontent.com/6596480/141699419-04b4f83e-10a2-4a81-a54f-f38ca9d825e3.png)

---
German:

![image](https://user-images.githubusercontent.com/6596480/141699489-412a0238-931c-44b3-a017-bc1b3f7f0221.png)

**Comment by pyrog** [comment]
Thank you very much Marc 😄
