### ISSUE TITLE
RouteRedundantNodes

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#234]
A route with start and end nodes with the same name containing " - " raise RouteRedundantNodes fact.
E.g. [Les Choseaux - Verneys](https://knooppuntnet.nl/en/analysis/route/12224035)

The route have the tag `note=A - A` where A is the name of the nodes (i.e. **Les Choseaux - Verneys**) to solve #233

<img width="594" alt="Les Choseaux - Verneys" src="https://user-images.githubusercontent.com/2158081/141421645-04186cfa-ccd4-4691-8f22-9debea0d1709.png">

PS: The official name of theses node is probably **Les Choseaux Verneys** or **Les Choseaux-Verneys** but a fact shouldn't be raised for start and end nodes that have the same name.

**Comment by pyrog** [comment]
Same issue with Route [Bois du Plan - sud - Les Gorges de la Valloirette](https://knooppuntnet.nl/en/analysis/route/12250237)

**Comment by vmarc** [comment]
At this moment the analysis logic cannot derive node names from "Les Choseaux - Verneys - Les Choseaux - Verneys". It is unclear how to make the logic such that it picks the right " - " to split up the two node names (based on the route name string only).

Route name "Les Choseaux-Verneys - Les Choseaux-Verneys" would work ok.

Another option could perhaps be to come up with a different separator, as in "Les Choseaux - Verneys | Les Choseaux - Verneys".

Another alternative in release 4 is to leave out the _note_ tag in the route relation, so that the route name is derived from the node names (but then no route names in JOSM).
