### ISSUE TITLE
Zombie  networks

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#238]
I tagged route as node network by mistake.
After cleaning, the "fake" networks are still displayed 😢 

[French networks](https://knooppuntnet.nl/en/analysis/hiking/fr/networks) 
<img width="50%" alt="Capture d’écran 2021-11-15 à 15 46 35" src="https://user-images.githubusercontent.com/2158081/141801604-438e7feb-9824-4493-9fcf-09e9365dcb6c.png">

Example relation 13442046
- https://knooppuntnet.nl/en/analysis/network/13442046
<img width="50%" alt="Capture d’écran 2021-11-15 à 15 47 34" src="https://user-images.githubusercontent.com/2158081/141801817-efed9730-222f-4a97-8511-fcccb65b6742.png">

- https://knooppuntnet.nl/en/analysis/route/13442046
<img width="462" alt="Capture d’écran 2021-11-15 à 15 49 34" src="https://user-images.githubusercontent.com/2158081/141802093-9044caf7-72a9-402e-9b1b-7c03ca1315fc.png">

**Comment by vmarc** [comment]
I believe this issue is similar to (or even the same as) issues #47, #49, #50, #51,  #94 and I think also #61. 

The zombie networks have been manually set to non-active in the database. This way they do not show up in the reporting anymore.  In release 4.0 the analysis logic will change significantly in this area.  We will need to explicitly test this case to make sure this problem is resolved then.

**Comment by vmarc** [comment]
Fixed in release v4.0 (currently only on experimental).

---

This history of network [13442046](https://www.openstreetmap.org/relation/13442046) before the change:

![network-history-before](https://user-images.githubusercontent.com/6596480/148644803-ab07bec1-2634-4aaf-86be-503f75dc8cd6.png)

- The changeset (113808106) where the network changed to a route is missing from the history.
- While processing changeset 113844359 on nov 16th, the analysis logic still thinks that the network exists.

---

This history of the network after the change:

![network-history-after](https://user-images.githubusercontent.com/6596480/148644818-b000f46d-4f7a-4166-872c-7830f88ab6c6.png)

- The change from network to route in changeset 113808106 is properly recognized as a network deletion.
- On nov 16th, the network does not exist anymore; so nothing in the history for changeset 113844359.
