### ISSUE TITLE
Node zombie network

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#244]
Node [Changin](https://knooppuntnet.nl/en/analysis/node/2585771891) was moved from [Cœur du Jura](https://knooppuntnet.nl/en/analysis/network/13438459) to [ECLA](https://knooppuntnet.nl/en/analysis/network/13464389) but Cœur du Jura is still displayed 😢
Similar to #238

<img width="50%" alt="Node Changin in Knooppuntnet" src="https://user-images.githubusercontent.com/2158081/143951092-9ef2a076-64e1-434a-a5ad-79e2b72c0cb7.png">

<img width="50%" alt="Node Changin in OpenStreetMap" src="https://user-images.githubusercontent.com/2158081/143951255-69ebcedf-9c0f-4cfe-82c3-ef90ce25a184.png">

**Comment by vmarc** [comment]
Node [Changin](https://knooppuntnet.nl/en/analysis/node/2585771891) is still considered part of network [Cœur du Jura](https://knooppuntnet.nl/en/analysis/network/13438459) because it is the start node of route [Changin - Fourche de Rouchasson](https://knooppuntnet.nl/en/analysis/route/13492652) which is part of [Cœur du Jura](https://knooppuntnet.nl/en/analysis/network/13438459).
