### ISSUE TITLE
Junction node not in network is only seen as error in the node list of a network

### ISSUE THREAD

**Issue by A67-A67** [vmarc/knooppuntnet#25]
All junction nodes should be grouped into a network. When one is not added, this is seen as an error in the node list of the network around this node. For example [here](https://knooppuntnet.nl/nl/network-nodes/1866014) someone forgot to add junction node 4 to the network relation (I hope it won't be solved quickly, otherwise the example doesn't work). However on the [page of node 4](https://knooppuntnet.nl/nl/node/1180949671) no errors are shown. Besides it is not shown on the [overview page](https://knooppuntnet.nl/nl/overview).

Because these errors are only shown in the long lists of nodes for each network, it is hard to correct them.

**Comment by vmarc** [comment]
@A67-A67 Thanks for reporting this.

The code has been changed in version v2.0.11, so that the node page shows fact _"NodeMemberMissing"_ (_"OntbrekendKnooppuntLid"_) when the node is missing as member in the network relation. 

The fact  _"NodeMemberMissing"_  is not shown when all the routes to/from the node have the role _"connection"_ in the network relation. The logic assumes that this means that the node does not belong to the network itself, but belongs to an adjecent network. In this case the node is also no longer shown in red in the network node lists.

The _"NodeMemberMissing"_ is also added in the overview page, and added to the pages that list the facts per country/networktype and per network.
