### ISSUE TITLE
Route monitor: "No GPX, so no known deviations" although everything is OK

### ISSUE THREAD

**Issue by hgcvm** [vmarc/knooppuntnet#257]
The route monitor sometimes says "No GPX, so no known deviations" on the route page itself. For example here: https://experimental.knooppuntnet.nl/en/monitor/groups/GRV/routes/P-GR130-oostcappel
In this case, this route relation matches the GPX file perfectly. So it's a confusing message. As there really is a GPX file.

**Comment by vmarc** [comment]
@hgcvm thanks for reporting this problem

Fixed in release 4.0.4

Improved information on route details page:

![issue257-details](https://user-images.githubusercontent.com/6596480/184316665-fcae5ce7-3e0d-4a94-b2c8-6f237cd3df67.png)

In addition, improved message on route map page (instead of empty table):

![issue257-map](https://user-images.githubusercontent.com/6596480/184316686-2247156b-0bc5-4829-9686-d628366db83a.png)
