### ISSUE TITLE
Locale should be optional in URL

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#276]
Locale is `nl` in this example:
https://knooppuntnet.nl/nl/analysis/route/12714489/map?position=51.46723229,4.47710314,15

It could be optional, so the web browser choose the user preferences.

Examples:
- https://knooppuntnet.nl/analysis/route/12714489/map?position=51.46723229,4.47710314,15
- https://knooppuntnet.nl/analysis/route/12714489/map?position=51.46723229,4.47710314,15&locale=nl

Part of #202.

**Comment by vmarc** [comment]
The language in the url is optional.  When no language is specified in the url, the user is redirected to the preferred language defined in the browser using the _Accept-Language_ HTTP header.  When I change the preferred language settings in my browser, I get knooppuntnet in that preferred language.

See also: [Angular internationalization deployment documentation](https://angular.dev/guide/i18n/deploy).

Using the referenced Angular internationalization mechanism, a separate application is generated for each language. This is why the language is the first element in the url after the domain name, rather than using a url parameter such as _"locale=nl"_.  This is also the approach recommended by Google: 

[Using locale-specific URLs](
https://developers.google.com/search/docs/specialty/international/managing-multi-regional-sites#locale-specific-urls).
