### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by hgcvm** [vmarc/knooppuntnet#280]
Currently, I cannot login https://knooppuntnet.be/en/login
I'm trying both Firefox and Chromium on Linux.

What information can I provide more to help solve my issue?
Thanks!

**Comment by vmarc** [comment]
@hgcvm thanks for reporting this problem!

I have tried to logout and login a couple of times, and at first it worked, but now it also fails consistently for me.  In the logfiles I can see that the knooppuntnet web server cannot connect to [openstreetmap.org](https://www.openstreetmap.org/oauth/request_token): _"Connection refused"_.

Need to follow up, perhaps this problem is only temporary and login will work again later.

**Comment by hgcvm** [comment]
I must say, now also JOSM gives a network error (connection refused). So most likely not a knooppuntnet issue.

**Comment by hgcvm** [comment]
Problem is gone. It must have been an OSM issue. Sorry for bothering.
