### ISSUE TITLE
Monitor - Format of reference date

### ISSUE THREAD

**Issue by hgcvm** [vmarc/knooppuntnet#287]
Thanks for the update vmarc!

I tried to fill in "Select the date at which the gpx trace was recorded or was known to be valid (default today): "
I manually filled in 02-12-2022 (and 2-12-2022) and got an error "Reference day is required", but when using the gui date chooser it worked. Strange thing is that the gui date chooser apparantly formats the date in exactly the same way as I manually typed it in.

I'm not sure if it's relevant, but the locale on my linux PC is set to en-us.

**Comment by vmarc** [comment]
@hgcvm thanks for reporting this problem

Problem is hopefully fixed in release 4.0.28, can you try?

Old computer wisdom: dates are complicated.

I have spent most of this Sunday trying to work out what was the problem, and how to fix it. I have tried multiple date parsing and formatting libraries, but ended up writing my own custom date adapter to make the Angular Material date picker work with our own Day class, and the supported languages: _'nl'_, _'fr'_, _'de'_ and _'en'_.

The way knooppuntnet is made, the locale setting on your local computer or browser should not have an impact. The date format is made to depend on the language used for the entire application (as found in the url after the domain name).

| language  |date format |
| ------------- | ------------- |
| nl  | DD-MM-YYYY  |
| fr  | DD/MM/YYYY  |
| de  | DD.MM.YYYY  |
| en  | YYYY-MM-DD  |
