### ISSUE TITLE
Monitor - No smiley face show with 0 deviations and 1 segment

### ISSUE THREAD

**Issue by gpol3000** [vmarc/knooppuntnet#288]
I have two routes that have no issues (0 deviations and 1 segment). But in the overview table, the smiley face doesn't show up:

https://knooppuntnet.be/en/monitor/groups/GRV/routes/p61
https://knooppuntnet.be/en/monitor/groups/GRV/routes/p54

Missing smileys in this table:
https://knooppuntnet.be/en/monitor/groups/GRV

It's again these very very short routes, mentioned in my previous issue as well.

**Comment by vmarc** [comment]
@gpol3000 thanks for reporting this problem

One of the conditions for the "smiley face" is that the length of the reference (gpx trace) is greater than zero. In the program logic, this length is expressed in kilometer.  In kilometer, the length of the mentioned routes is zero. Who would have thought that there would be long distance hiking routes with a length less than 1 kilometer?  I can see that it does make sense though for "aanloop".

The solution will be to use meters instead of kilometers for the route length.

**Comment by vmarc** [comment]
Fixed in release 4.0.31.
