### ISSUE TITLE
[Monitor] generate an openstreetmap.org link from map

### ISSUE THREAD

**Issue by StC-OSM** [vmarc/knooppuntnet#290]
When reviewing deviations or interruptions it would sometimes be useful to have a URL that points to the right area on openstreetmap.org. The link to JOSM is not always relevant to the ongoing task.

**Comment by vmarc** [comment]
@StC-OSM thanks for this suggestion

In order to better understand what you are looking for: what would be the reason to want go to the area of the deviation on openstreetmap.org?

If the main reason is to see the openstreetmap styled background tiles, then I think one option is to make these available in the knooppuntnet maps. In fact you can already set the osm tiles as background through a "hidden" [settings page](https://knooppuntnet.nl/en/settings) (select "Extra layers").  The standard is to use our own knooppuntnet generated background tiles, served from our own server. I guess when used for mapping purposes, using the osm background tiles from time to time would be fair use (see: [osm tile usage policy](https://operations.osmfoundation.org/policies/tiles/)).

Or do you see other reasons for going to openstreetmap.org?

**Comment by StC-OSM** [comment]
Hi,

my goal is to be able to edit the route with ID so as to fix issues.

St.

**Comment by vmarc** [comment]
@StC-OSM is the following what you wanted?

Click on the _"3 dots"_ button on the deviation, and select _"Go here in openstreetmap.org"_.

Alternatively, click on the _"openstreetmap.org"_ or _"iD"_ links on the right.  Thees links also work when zoomed on a detail of the map for example when examining osm segments.


![issue-290](https://user-images.githubusercontent.com/6596480/209205213-5fdbd106-77df-42e4-b11d-b8143a7a62f3.png)

**Comment by StC-OSM** [comment]
Great, yes!

St.
