### ISSUE TITLE
[Monitor] Default date of reference route seems wrong

### ISSUE THREAD

**Issue by pelderson** [vmarc/knooppuntnet#294]
Could here be something wrong with the default date setting of the reference?

When first setting the reference route (type OSM relation), I noticed that the changes I made that very day were shown as differences. I had not set the date myself but I used the default, because it said "default today". I did not actually check the date on the screen. 

I then changed to a gpx reference, no problem there. Then I wanted to change back to osm, and I noticed the date said dec 8 2022, which is not today (dec 12, 2022)

I have no problem setting the date myself, but if the page says "default today" I expect the default to be today!

**Comment by vmarc** [comment]
@pelderson thanks for reporting this problem

When adding a new route, the reference day that is already filled in by default is the current day. The user can change this day to document the moment that a gpx trace has been recorded.  When the reference type "osm" is selected, a day in the past can be selected to that all changes since that day become visible in the analysis.

With reference type "osm" and leaving the current day that was already filled in, the timestamp of the reference is midnight of that day. So the first analysis will show all changes made since midnight as differences. To be more precise, the reference timestamp is midnight in [UTC](https://nl.wikipedia.org/wiki/UTC) time (during winter 01:00h where we live).

Once a reference day has been selected, this day is kept in the route definition, also when changing the reference type from "osm" to "gpx" and back, unless the user explicitely changes the day when updating the route definition.

In release 4.0.33, the "default today" was removed from the day label as it is indeed misleading: the "default today" only applies when first adding the route.
