### ISSUE TITLE
"No map" for routes monitored without reference

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#300]
The map is empty and the message "No map" and smileys are displayed.

Related to #299

Example: [R2 Réunion - Traversée de la Réunion](https://knooppuntnet.nl/en/monitor/groups/fr-nwn/routes/R2/map)
<img width="45%" alt="Map" src="https://user-images.githubusercontent.com/2158081/209217166-00e3988d-646b-48d1-8206-157759f8afc2.png"> <img width="45%" alt="Details" src="https://user-images.githubusercontent.com/2158081/209217212-e650c17b-dfb7-4929-98b1-c5cf56b4fcff.png">

**Comment by pyrog** [comment]
KPN display segment list but display nothing.
This is probably because you don't have OSM data for this part of the world?

Is it the same issue or another ?

[GR R1 Tour du Piton des Neiges](https://knooppuntnet.nl/en/monitor/groups/fr-nwn/routes/GR%20R1/map)
<img width="45%" alt="map" src="https://user-images.githubusercontent.com/2158081/209225067-0129ec26-5604-4a10-a66d-0a3058f378ca.png"> <img width="45%" alt="Details" src="https://user-images.githubusercontent.com/2158081/209225214-840ffe2f-5bd2-4d8a-ba18-7972bb1221fa.png" valign="top">

**Comment by vmarc** [comment]
@pyrog thanks for reporting this issue

Fixed in release 4.0.35.

The issue with both routes was the same: the map did not get displayed for latitudes less than zero. This has been fixed in the code.

The knooppuntnet overpass database contains all OSM data for the entire world (and the complete history since september 2012). 

The knooppuntnet background tiles however are only generated for Austria, Belgium, Germany, Luxembourg, Netherlands, Poland, Spain and France, but all of this only within [bounding box -9.3, 36.0, 24.5, 55.15](http://bboxfinder.com/#36.000000,-9.300000,55.150000,24.500000). This is why for given routes by default no background tiles are displayed. You can enable the OpenStreetMap tiles in the layers popup menu. The OSM tiles have to be re-enabled every time a new map is displayed, this is done because we still want the knooppuntnet tiles to always be the default ([osm tile usage policy](https://operations.osmfoundation.org/policies/tiles/)).

**Comment by pyrog** [comment]
Thank you for the fix and the explanations.

OSM tiles are nice (to see i.e. guideposts) 😎
…so I added feature request #301
