### ISSUE TITLE
KPN changeset URL is not "compatible" with OSM changeset URL

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#308]
From changeset iD, it's easy to build it's URL, but it's not trivial to do it with KPN URL.
Changeset 132783596
- OSM https://www.openstreetmap.org/changeset/132783596 👍 
- KPN https://knooppuntnet.nl/en/analysis/changeset/132783596/5456667 👎 

Is it possible to remove (or to ignore) the suffix in KPN changeset URL ?

5456667 suffix is displayed **005/456/667**.
What is his meaning ?

**Comment by vmarc** [comment]
The suffix _005/456/667_ refers to the [minute diff](https://wiki.openstreetmap.org/wiki/Planet.osm/diffs) in which the changeset was replicated from OpenStreetMap.

A given changeset can be replicated from OSM in multiple minute diffs. Knooppuntnet processes the incoming information per minute diff.  This way one changeset can result in multiple entries in the knooppuntnet analysis database.  In order to uniquely identify the entry in the database, the minute diff identifier has to be added in the url.

In release 4.3.61 the logic has been changed so that the minute diff identifier can be omitted from the url.  When there are multiple entries in the database, the minute diff identifiers are listed, and the user can select which minute diff to go to.  If there is only one minute diff (the vast majority of changesets), then the information in that minute diff is shown immediately.

[example changeset split up over multiple minute diffs](https://knooppuntnet.nl/en/analysis/changeset/99985530)

**Comment by pyrog** [comment]
I preferred to see all the splits in one page, but this is a good solution : 
an app like OSMCha could now open easily the changes in KPN 😃

Thanks.

**Comment by vmarc** [comment]
In release 4.3.62 the changeset page has been changed to contain the changeset details of all minute diffs (no more links to the individual mininute diff changeset pages).
