### ISSUE TITLE
oneway:bicycle=no on roundabout (e.g. with cycleway=track) causes broken route

### ISSUE THREAD

**Issue by A67-A67** [vmarc/knooppuntnet#31]
[This route](https://knooppuntnet.nl/nl/route/4271) seems to be broken at the roundabout where the route uses a two-way track around the roundabout. The combination junction=roundabout and oneway:bicycle=no implies a two-way roundabout for cyclists. The table doesn't show a 'Yes' in the one way column for these ways. However the route still seems to be broken at this point.

**Comment by vmarc** [comment]
@A67-A67 Thanks for reporting this problem!

While trying to find the path from start to end node and vice versa, the analysis logic considered a way with _junction=roundabout_ to always be oneway, independent from any additional tags on the way.

This has now been changed so that the _junction=roundabout_ tag is no longer considered separately in path finding logic. Instead, tag _junction=roundabout_ is included in the _one way logic_, and the oneway characteristic of _junction=roundabout_ gets overruled by _oneway:bicycle=no_. 

You can review the complete oneway logic in the [code](https://github.com/vmarc/knooppuntnet/blob/develop/production/core/src/main/scala/kpn/core/engine/analysis/OneWayAnalyzer.scala) and the related [tests](https://github.com/vmarc/knooppuntnet/blob/develop/production/core/src/test/scala/kpn/core/engine/analysis/OneWayAnalyzerTest.scala).

The relevant part of the path finding logic that was updated is in [code](https://github.com/vmarc/knooppuntnet/blob/develop/production/core/src/main/scala/kpn/core/engine/analysis/NodeFragmentConnectionAnalyzer.scala) and [test](https://github.com/vmarc/knooppuntnet/blob/develop/production/core/src/test/scala/kpn/core/engine/analysis/NodeFragmentConnectionAnalyzerTest.scala).

With v2.0.11, route [05-08](https://knooppuntnet.nl/nl/route/4271) will no longer be considered broken (see [test](https://github.com/vmarc/knooppuntnet/blob/develop/production/core/src/test/scala/kpn/core/engine/analysis/caseStudies/Issue31.scala)).
