### ISSUE TITLE
[Monitor] Bug when changing reference

### ISSUE THREAD

**Issue by StC-OSM** [vmarc/knooppuntnet#311]
Part of the process we have chosen with a route manager is that we use a GPX reference while creating/fixing a route in OSM, then we switch to an OSM reference so as to monitor changes (generally damage) that occur in the route.

Currently when we perform this switch, strange things happen:
 - in order to make sure that the OSM reference is taken into account when computing deviations, I must select a reference date posterior to the current day. Usually I choose tomorrow.
  - ultimately, the route is still displayed with a GPX reference in the table, with results that are computed with an OSM reference

**Comment by vmarc** [comment]
Fixed in next release (not published yet).

The monitor route definition update logic now correctly handles changing the reference type from _"gpx"_ to _"osm"_.

When setting the monitor route reference day in the route definition, the state of the route at that day at midnight (UTC) is used as the reference to perform the analysis against.  This is why you need to set the reference day to "tomorrow" if you want to see deviations that were introduced between midnight and the time of route creation.  This can be confusing.

To avoid confusion, the existing reference type selection has been renamed to _"The OSM relation at a given moment in the past"_ and an extra option _"The OSM relation at this moment"_ has been added.  When selecting the latter, no reference day has to be entered by the user, and the current system time is used instead (changes since midnight are taken into account).

> ![reference-type](https://github.com/vmarc/knooppuntnet/assets/6596480/196aa54d-7c60-410f-b763-0911ecfa79f6)

**Comment by vmarc** [comment]
Solution published in release v4.1.0.
