### ISSUE TITLE
RouteWithoutWays list nothing

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#409]
The analyser find 1 route in France without ways but display "No facts 😄"
[RouteWithoutWays](https://knooppuntnet.nl/en/analysis/hiking/fr/facts/RouteWithoutWays) (1)

Also in [Netherlands](https://knooppuntnet.nl/en/analysis/hiking/nl/facts).

**Comment by vmarc** [comment]
There currently is 1 hiking route without ways in France.

- The [analysis overview page](https://knooppuntnet.nl/en/analysis/overview) shows route count 1.

- The [subset facts page](https://knooppuntnet.nl/en/analysis/hiking/fr/facts) also shows route count 1.

- The [network facts page](https://knooppuntnet.nl/en/analysis/network/13511365/facts#RouteWithoutWays) also shows route count 1.

- The [fact details page](https://knooppuntnet.nl/en/analysis/hiking/fr/facts/RouteWithoutWays) does not show the route.

- The [location facts page](https://knooppuntnet.nl/en/analysis/hiking/fr/facts/RouteWithoutWays) does not show the route.

---

What is the cause of this discrepancy?

Short:

The pages that show route counts use queries that get the information from the _'statistics'_ collection
in the mongodb analysis database, which in turn contains counts based on the information in the _'network-infos'_ collection.

The pages that show the actual route information have queries that get the information directly from the _'routes'_ collection.  The _'routes'_ collection does not contain any location information for routes without ways or nodes.

Long:

The one route in France reported in the route count for fact _RouteWithoutWays_ is [17144686](https://knooppuntnet.nl/en/analysis/route/17144686).

In the analysis database the route itself has no location information. The location information (country, municipality, etc.) is derived from the coordinates of the nodes and the routes in the route relation. This route does not contain any ways and any nodes (hence the fact reported: _RouteWithoutWays_), so there are no coordinates to derive the location from.  

The route does belong to a network though: [Porte de Maurienne](https://knooppuntnet.nl/en/analysis/network/13511365/facts#RouteWithoutWays).

In this network, the route is reported with facts: _RouteWithoutWays_, _RouteWithoutNodes_, _RouteNameMissing_ and _RouteUnexpectedRelation_.  The country of a network is derived from all routes and nodes in that network. This network does contain other routes with coordinates, so the analysis
logic can determine the location of the network.

The fact count queries indirectly use the information in the _'network-infos'_ collection.  For _'France hiking routes with RouteWithoutWays'_ the query counts all routes within all hiking networks in France.  The route without ways is counted.

The queries looking for the route details use the _'routes'_ collection directly, and routes without ways or nodes are not found because they have no location information.

See: [issue analysis code](https://github.com/vmarc/knooppuntnet/blob/3891fe15b1fb4e9c8d8e402e0216d42dc7819b88/server/src/main/scala/kpn/core/tools/support/FactCheckTool.scala).

**Comment by vmarc** [comment]
The route location analysis logic has been changed to look for the country in the networks that the route belongs to if the relation of the route itself does not contain any members with coordinates.
