### ISSUE TITLE
Please make colours more intuitive

### ISSUE THREAD

**Issue by BertMule** [vmarc/knooppuntnet#421]
Request for simple improvement of GUI: swap colours to more intuitive setting.

- Paved: blue.
- Unpaved: green.
- Unknown: orange.

I am particularly referring to [hiking](https://knooppuntnet.nl/en/map/hiking).
But the same would apply to [cycling](https://knooppuntnet.nl/en/map/cycling).

**Comment by vmarc** [comment]
@BertMule thanks for this suggestion

I am willing to change the colours as requested, but I guess what is to be considered "intuitive" colours, can be a bit subjective.

Do you perhaps have example maps where the colours you are requesting are used?

I think the explanation for the use of the existing colours is more or less as follows:  the colour "green" is generally associated with something "good" or "positive".  Especially in the cycling network "paved" is good (better than "unpaved").  The colour "orange" for me has the association with "sand": "unpaved".  The "blue" for "unknown" was chosen because it stands out well against the green and orange and the OSM or OpenMapTiles background colours.

The mostly "green" routes work well with the "red" that was chosen for the open data layers ("Toerisme Vlaanderen" and "Routedatabank Nederland"). Dark blue on dark red would not work as good I imagine.

On the other hand the "pink" colour used to indicate the planned route seems to work better on "blue and green" than on  "green and orange".  The "yellow" highlight on hovering over node or route seems to work ok for all colours.

**Comment by vmarc** [comment]
I guess the colours used in the monitor maps can stay as they are?

See [example monitor map](https://knooppuntnet.nl/en/monitor/groups/NL-LAW/routes/LAW%201-1/map?mode=comparison&reference=false&matches=true&deviations=true&osm-relation=true&sub-relation-index=0&position=53.37518630,6.16072324,16).

**Comment by StC-OSM** [comment]
It might be useful to think in terms of "color coding systems".  Are we looking for a system to represent "good/bad/unknown"? Or "green as grass / gray as pavement / unknown" ? Other? In any case, "intuitive" may be usefully equated with "using similarities with color coding systems that the users already know"

It would also be useful to take into account the possible interferences with other color coding systems in Knooppuntnet. Green is already used for "ok" (versus red for "not ok") and for "objects of interest" (vs gray for "objects of context"). Using green for "unpaved" may be consistent with existing uses (if we agree that unpaved is good). Using gray may be more ambiguous.

Maybe green / dark grey / light grey would be a good compromise for the two possible systems I mentioned above? Or green / dark grey / red if you want to insist on "information missing is very naughty".

**Comment by BertMule** [comment]
Thanks for your reaction

I don't know those monitor maps.

Good or bad is subjective. And as a hiker my preference is even opposite, I prefer unpaved.

My colours would be objectively associated to physical reality. Most clearly unpaved paths over grass.

Here is an [example ](https://knooppuntnet.nl/en/map/hiking?mode=surface&position=52.12256776%2C4.50960506%2C16&result=compact&layers=background%2Chiking&poi-layers=hiking-biking%2Clandmarks%2Crestaurants%2Cplaces-to-stay%2Ctourism) I have been working on.
- I would be correcting the current blue near 81 and 82 soon. But in contrast: 81-82 **should** be blue in my mind,  as it is through streets.
- 35-34 is entirely over grass (except for the current green concrete part). I would prefer to see those green. Which is also intuitive amidst the meadows.

I am just looking at the existing colours in probably the only part I have really used so far. 
So I can't oversee the other usages.

**Comment by vmarc** [comment]
Colours changed in v4.3.44.

**Comment by BertMule** [comment]
> Colours changed in v4.3.44.

Just noticed.
I think that's what I requested.

Thanks.

**Comment by BertMule** [comment]
Really a detail.

Choice of colours could be more contrasting to the underlying map, particularly the green. The orange looks like too much like a  highway.
In general, they could be a bit darker and 'harder'.

**Comment by vmarc** [comment]
@BertMule could you maybe propose specific rgb colour values (perhaps using a [colorpicker](https://www.w3schools.com/colors/colors_picker.asp))?
