### ISSUE TITLE
Route incorrectly seen as orphan route

### ISSUE THREAD

**Issue by A67-A67** [vmarc/knooppuntnet#46]
[This route](https://knooppuntnet.nl/nl/route/8304581) is seen as an orphan route in Knooppuntnet. On [Openstreetmap](https://www.openstreetmap.org/relation/8304581) it is visible that the route is part of the Velden en Meersen network.

**Comment by vmarc** [comment]
@A67-A67 Thanks for reporting this problem.

The document with id "network:8300603" in couchdb does not contain route 8304581. This is why the route is seen as an orphan route.  This is strange because in de overpass database, network 8300603 does contain the route, and the last time the network was retrieved from overpass, the query result also contained the route.

This has to be further investigated.

**Comment by vmarc** [comment]
relation(8300603);(>>;);out meta;

./05/08/20/37/54/relation-8300603.xml.gz
./05/08/20/37/57/relation-8300603.xml.gz

After recreating the database from scratch, all is ok.
