### ISSUE TITLE
Rename "Horse" to "Riding" in the UI

### ISSUE THREAD

**Issue by Hufkratzer** [vmarc/knooppuntnet#53]
Would you mind to rename "Horse" to "Riding" in the UI? 

The access key [horse=*](https://wiki.openstreetmap.org/wiki/Key:horse) is for riders and not for horses in general. For horse-drawn vehicles we have [carriage=*](https://wiki.openstreetmap.org/wiki/Key:carriage).

See also:
* [access=*](https://wiki.openstreetmap.org/wiki/Key:access) 
* [route=horse](https://wiki.openstreetmap.org/wiki/Tag:route%3Dhorse) 
* [Waymarked Trails Riding Map](https://riding.waymarkedtrails.org/help?lang=en)

**Comment by vmarc** [comment]
The user interface has been changed to show "Horse riding" instead of "Horse". This was done both in the existing userinterface (in next release v2.0.17), and in the upcoming version 3.0.0 Angular based user interface. To avoid future confusion, not only the user interface was changed, but also the internal name of the network type in the code. For version 3.0.0, the url's for subset specific pages and map tiles also have been adapted to use "horse-riding" instead of "horse".

The term "Horse riding" was choosen over just "Riding" to avoid possible confusion with bycicle riding.
