### ISSUE TITLE
Ten onrechte melding Overlappende segmenten

### ISSUE THREAD

**Issue by dvdhoven** [vmarc/knooppuntnet#54]
Bij route 01-45 van rcn netwerk Stadsregio Arnhem-Nijmegen wordt ten onrechte een melding Overlappende segmenten gegeven.
Hier delen de heen- en de terugroute een stukje weg. Dat komt omdat de routes net anders lopen, dan "normaal", de heenroute loopt aan de "bovenkant" en de terugroute aan de "onderkant" en daarom kruisen de routes elkaar
Maar dit is geen overlappend segment!!!

De analyse moet voor overlappend segment checken of de segmenten in volgorde tegen elkaar aan liggen, zoniet dan is het geen overlappend segment.
De route editor van JOSM geeft deze route ook keurig weer.

En ik heb geen zin meer om moeizaam steenkolen Engels te gaan bedenken. Nederlands is mijn moers taal, dus deze melding in het Nederlands

**Comment by vmarc** [comment]
@dvdhoven dank voor het melden van dit probleem

Uiteraard zijn meldingen in het Nederlands welkom. De tekst op van de README op de github project startpagina is in die zin aangepast.

**Comment by vmarc** [comment]
The fact **RouteOverlappingWays** (OverlappendeWegen) was introduced at the time that the German cycling routes were added to the analysis. This validation was used to exclude some very very large German routes with lots of gaps in them and overlapping ways, and that were not even part of a node network. These routes needed to be excluded because they did take over 90% of the computer resources while processing the change history. These routes are currently excluded through the blacklist, so the additional validation is currently not needed anymore.  After implementation of #57, this blacklist will also not be needed anymore.

The logic for fact **RouteOverlappingWays** has been disabled, and the database has been regenerated.
