### ISSUE TITLE
MTB-network in analysis for bicycle

### ISSUE THREAD

**Issue by A67-A67** [vmarc/knooppuntnet#61]
The [MTB-netwerk Regio Twente](https://knooppuntnet.nl/nl/network/2827679) is now in the analysis. It has a route=mtb instead of a route=bicycle, but mtb-routes also use the network=Xcn. 

This was incorrectly tagged as a network=rcn, but after I changed it to the correct network=lcn the network isn't being updated anymore and it stays in the analysis including all its errors.

**Comment by vmarc** [comment]
@A67-A67 thanks for reporting this problem

I have manually removed the network from the analysis database, so that it disappears from the reporting for now.

The tags _route=mbt_ or _route=bicycle_ do not get interpreted by the analysis logic in network relations. 

The change from _rcn_ to _lcn_ however, should have been picked up by the analysis, but it wasn't. This needs to be further investigated.

**Comment by vmarc** [comment]
This problem may be the same as #47, #49, #50 and #51.

**Comment by vmarc** [comment]
Relation [2827679](https://www.openstreetmap.org/relation/2827679) does not have the "network:type=network_node" tag and is therefore not (mis-)interpreted anymore.
