### ISSUE TITLE
Feature request: support node networks in Austria too

### ISSUE THREAD

**Issue by robhubi** [vmarc/knooppuntnet#68]
We are happy to have the first cycle node system in Austria now also available in OSM. It would be great if knooppuntnet could add Austria to the list of supported countries. The sophisticated analysis tools would be a great help in maintaining the network.

Name:	nimm's Radl Murtal Radknotensystem
Link: https://www.openstreetmap.org/relation/10514412
Description: https://wiki.openstreetmap.org/wiki/WikiProject_Austria/Radknotenpunktnetze

Thanks a lot
Robert

**Comment by vmarc** [comment]
@robhubi Thanks for issuing this feature request. I will have a look into this.

**Comment by vmarc** [comment]
Support for node networks in Austria is added.

One interesting fact I learned about Austria is that the country boundaries contain a point where the border lines go in 4 different directions ([Jungholz quadripoint](https://en.wikipedia.org/wiki/Jungholz)). The [knooppuntnet logic that creates the country boundary polygons](https://github.com/vmarc/knooppuntnet/blob/develop/server/src/main/scala/kpn/core/tools/country/CountryBoundaryTool.scala) chocked on this, and some special code had to be added to work around this problem.

Austria support is also added in the new version of knooppuntnet (with [route planner](https://experimental.knooppuntnet.nl/en/map/cycling)) which is still work in progress at this moment:

![route-planner](https://user-images.githubusercontent.com/6596480/71783071-de2f2480-2fe1-11ea-84a1-9700702f0dc2.png)

In the new version, the osm background tiles are served from the knooppuntnet website (instead of openstreetmap.org), and the Austria have been added also. There are more than 1,1 million tiles now.

Point of interest support in the route planner in the new version is currently stil limited to Belgium and The Netherlands. France, Germany and Austria should follow later, when the poi logic is it bit further improved.

The intention is for new version to become available in the German and French also. My German and French are not good enough to do this myself. If anybody reading this can [help out](https://experimental.knooppuntnet.nl/en/docs/en.html#_translate_application_to_different_language) with this, that would be very welcome.

**Comment by robhubi** [comment]
Great! This is a huge support!
Thank you very much!
Robert
